// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using ShopPanel.Models.Context;
using System;

namespace ShopPanel.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230719075645_m1")]
    partial class m1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.AdvertisePlanState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("adv_id");

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<DateTime>("expiredateml");

                    b.Property<string>("expiredatesh");

                    b.Property<int>("plan_id");

                    b.Property<DateTime>("startdateml");

                    b.Property<string>("startdatesh");

                    b.Property<byte>("status");

                    b.HasKey("Id");

                    b.HasIndex("adv_id");

                    b.HasIndex("plan_id");

                    b.ToTable("Tbl_AdvertisePlanState");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.ApplicationRoles", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.Property<string>("RoleLevel");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.ApplicationUsers", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("BirthDayDate");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserImagePath");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<byte>("gender");

                    b.Property<bool>("isEnable");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.Appsetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("about");

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<string>("email");

                    b.Property<string>("ownername");

                    b.Property<string>("phone");

                    b.Property<string>("shabacode");

                    b.Property<byte>("status");

                    b.Property<string>("user_id");

                    b.Property<int>("wage");

                    b.HasKey("Id");

                    b.HasIndex("user_id");

                    b.ToTable("Tbl_Appsetting");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.Appversion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<string>("desc");

                    b.Property<bool>("isEnable");

                    b.Property<string>("link");

                    b.Property<byte>("status");

                    b.Property<int>("versionCode");

                    b.Property<string>("versionName");

                    b.HasKey("Id");

                    b.ToTable("Tbl_Appversion");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.bannerImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("banner_id");

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<string>("image");

                    b.Property<byte>("status");

                    b.HasKey("Id");

                    b.HasIndex("banner_id");

                    b.ToTable("Tbl_BannerImage");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.Buy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("buyer_id");

                    b.Property<int>("buyeradd_id");

                    b.Property<byte>("buystatus");

                    b.Property<int>("color_id");

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<bool>("isenable");

                    b.Property<byte>("posttype");

                    b.Property<int>("price");

                    b.Property<long>("product_id");

                    b.Property<int>("qty");

                    b.Property<long>("shop_id");

                    b.Property<int>("size_id");

                    b.Property<byte>("status");

                    b.Property<int>("totalprice");

                    b.HasKey("Id");

                    b.HasIndex("buyer_id");

                    b.HasIndex("buyeradd_id");

                    b.HasIndex("product_id");

                    b.HasIndex("shop_id");

                    b.ToTable("Tbl_Buy");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.Buycheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("buy_id");

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<string>("desc");

                    b.Property<bool>("isenable");

                    b.Property<byte>("status");

                    b.HasKey("Id");

                    b.HasIndex("buy_id");

                    b.ToTable("Tbl_BuyCheck");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ParentId");

                    b.Property<string>("Title");

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<string>("image");

                    b.Property<bool>("isenable");

                    b.Property<byte>("status");

                    b.Property<byte>("type");

                    b.HasKey("Id");

                    b.ToTable("Tbl_Category");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.Checkout", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("bank_id");

                    b.Property<int>("checkoutprice");

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<long>("seller_id");

                    b.Property<long>("shop_id");

                    b.Property<byte>("status");

                    b.HasKey("Id");

                    b.HasIndex("bank_id");

                    b.HasIndex("seller_id");

                    b.HasIndex("shop_id");

                    b.ToTable("Tbl_Checkout");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.CheckoutRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("bank_id");

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<int>("requestprice");

                    b.Property<long>("seller_id");

                    b.Property<long>("shop_id");

                    b.Property<byte>("status");

                    b.HasKey("Id");

                    b.HasIndex("bank_id");

                    b.HasIndex("seller_id");

                    b.HasIndex("shop_id");

                    b.ToTable("Tbl_CheckoutRequest");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<int>("ostan_id");

                    b.Property<byte>("status");

                    b.Property<string>("title");

                    b.HasKey("Id");

                    b.HasIndex("ostan_id");

                    b.ToTable("Tbl_City");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("code");

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<bool>("isenable");

                    b.Property<string>("name");

                    b.Property<string>("nameen");

                    b.Property<byte>("status");

                    b.HasKey("Id");

                    b.ToTable("Tbl_Color");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("appuser_id");

                    b.Property<string>("body");

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<bool>("isEnable");

                    b.Property<long>("product_id");

                    b.Property<byte>("status");

                    b.Property<string>("title");

                    b.HasKey("Id");

                    b.HasIndex("appuser_id");

                    b.HasIndex("product_id");

                    b.ToTable("Tbl_comment");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.ContactUs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("appuser_id");

                    b.Property<string>("body");

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<bool>("isenable");

                    b.Property<byte>("status");

                    b.Property<string>("title");

                    b.HasKey("Id");

                    b.HasIndex("appuser_id");

                    b.ToTable("Tbl_Contact");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.FileManager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<string>("path");

                    b.Property<byte>("status");

                    b.HasKey("Id");

                    b.ToTable("Tbl_filemanager");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.FollowShop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<bool>("isenable");

                    b.Property<long>("shop_id");

                    b.Property<byte>("status");

                    b.Property<long>("userapp_id");

                    b.Property<string>("usertoken");

                    b.HasKey("Id");

                    b.HasIndex("shop_id");

                    b.HasIndex("userapp_id");

                    b.ToTable("Tbl_FollowShop");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("appuser_id");

                    b.Property<string>("codeorder");

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<DateTime>("finishdateMiladi");

                    b.Property<string>("finishdateShamsi");

                    b.Property<bool>("isEnable");

                    b.Property<bool>("isfinish");

                    b.Property<int>("postprice");

                    b.Property<byte>("posttype");

                    b.Property<byte>("status");

                    b.Property<int>("sumprice");

                    b.Property<int>("useradd_id");

                    b.HasKey("Id");

                    b.HasIndex("appuser_id");

                    b.ToTable("Tbl_Order");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.orderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("color_id");

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<bool>("isenable");

                    b.Property<long>("order_id");

                    b.Property<int>("price");

                    b.Property<long>("product_id");

                    b.Property<int>("qty");

                    b.Property<long>("shop_id");

                    b.Property<int>("size_id");

                    b.Property<byte>("status");

                    b.Property<int>("totalprice");

                    b.HasKey("Id");

                    b.HasIndex("order_id");

                    b.HasIndex("product_id");

                    b.HasIndex("shop_id");

                    b.ToTable("Tbl_orderdetail");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.Ostan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<byte>("status");

                    b.Property<string>("title");

                    b.HasKey("Id");

                    b.ToTable("Tbl_Ostans");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.Part", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<bool>("isenable");

                    b.Property<string>("key");

                    b.Property<byte>("status");

                    b.HasKey("Id");

                    b.ToTable("Tbl_PropertyPart");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("amount");

                    b.Property<long>("appuser_id");

                    b.Property<string>("comment");

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<bool>("isSuccess");

                    b.Property<bool>("isenable");

                    b.Property<long>("order_id");

                    b.Property<string>("refid");

                    b.Property<byte>("status");

                    b.HasKey("Id");

                    b.HasIndex("appuser_id");

                    b.ToTable("Tbl_payment");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte>("count");

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<string>("desc");

                    b.Property<bool>("isEnable");

                    b.Property<string>("nameen");

                    b.Property<string>("namefa");

                    b.Property<int>("offpercent");

                    b.Property<byte>("plantype");

                    b.Property<int>("price");

                    b.Property<byte>("status");

                    b.Property<byte>("type");

                    b.HasKey("Id");

                    b.ToTable("Tbl_Plan");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.ProdProp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<long>("product_id");

                    b.Property<int>("property_id");

                    b.Property<byte>("status");

                    b.Property<string>("value");

                    b.HasKey("Id");

                    b.HasIndex("product_id");

                    b.HasIndex("property_id");

                    b.ToTable("Tbl_ProductProperty");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("User_id");

                    b.Property<int>("brand_id");

                    b.Property<int>("cat_id");

                    b.Property<string>("code");

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<string>("desc");

                    b.Property<bool>("enable");

                    b.Property<string>("garanty");

                    b.Property<string>("image");

                    b.Property<bool>("isexist");

                    b.Property<bool>("ispublish");

                    b.Property<string>("keyword");

                    b.Property<int>("likeCount");

                    b.Property<int>("offpercent");

                    b.Property<long>("price");

                    b.Property<int>("qty");

                    b.Property<long>("seller_id");

                    b.Property<long>("shop_id");

                    b.Property<byte>("status");

                    b.Property<string>("summary");

                    b.Property<string>("title");

                    b.Property<int>("viewCount");

                    b.Property<int>("weight");

                    b.HasKey("Id");

                    b.HasIndex("User_id");

                    b.HasIndex("brand_id");

                    b.HasIndex("cat_id");

                    b.HasIndex("seller_id");

                    b.HasIndex("shop_id");

                    b.ToTable("Tbl_Products");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.ProductBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<bool>("isenable");

                    b.Property<string>("name");

                    b.Property<string>("nameen");

                    b.Property<byte>("status");

                    b.HasKey("Id");

                    b.ToTable("Tbl_Brand");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.ProductColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("color_id");

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<long>("product_id");

                    b.Property<byte>("status");

                    b.HasKey("Id");

                    b.HasIndex("color_id");

                    b.HasIndex("product_id");

                    b.ToTable("Tbl_ProductColor");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.ProductFav", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("appuser_id");

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<long>("product_id");

                    b.Property<byte>("status");

                    b.HasKey("Id");

                    b.ToTable("Tbl_Favorite");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.ProductGallary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<string>("imagepath");

                    b.Property<long>("product_id");

                    b.Property<byte>("status");

                    b.HasKey("Id");

                    b.HasIndex("product_id");

                    b.ToTable("Tbl_ProductGallary");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.ProductProperties", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<long>("product_id");

                    b.Property<int>("properties_id");

                    b.Property<int>("propertiesvalue_id");

                    b.Property<byte>("status");

                    b.HasKey("Id");

                    b.HasIndex("product_id");

                    b.HasIndex("properties_id");

                    b.HasIndex("propertiesvalue_id");

                    b.ToTable("Tbl_ProductProperties");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.ProductSeller", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<bool>("isEnable");

                    b.Property<bool>("isExist");

                    b.Property<bool>("ismainseller");

                    b.Property<byte>("offpercent");

                    b.Property<long>("price");

                    b.Property<byte>("productType");

                    b.Property<long>("product_id");

                    b.Property<byte>("qty");

                    b.Property<long>("seller_id");

                    b.Property<long>("shop_id");

                    b.Property<byte>("status");

                    b.HasKey("Id");

                    b.HasIndex("product_id");

                    b.HasIndex("seller_id");

                    b.HasIndex("shop_id");

                    b.ToTable("Tbl_ProductSeller");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.ProductSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<long>("product_id");

                    b.Property<int>("size_id");

                    b.Property<byte>("status");

                    b.HasKey("Id");

                    b.HasIndex("product_id");

                    b.HasIndex("size_id");

                    b.ToTable("Tbl_ProductSize");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.Properties", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("category_id");

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<bool>("isEnable");

                    b.Property<string>("name");

                    b.Property<byte>("status");

                    b.HasKey("Id");

                    b.HasIndex("category_id");

                    b.ToTable("Tbl_Properties");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.PropertiesValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<bool>("isEnable");

                    b.Property<int>("properties_id");

                    b.Property<byte>("status");

                    b.Property<string>("value");

                    b.HasKey("Id");

                    b.HasIndex("properties_id");

                    b.ToTable("Tbl_PropertiesValue");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("cat_id");

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<bool>("isenable");

                    b.Property<string>("name");

                    b.Property<int>("part_id");

                    b.Property<byte>("status");

                    b.HasKey("Id");

                    b.HasIndex("cat_id");

                    b.HasIndex("part_id");

                    b.ToTable("Tbl_Property");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.ReportProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("appuser_id");

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<bool>("isenable");

                    b.Property<string>("message");

                    b.Property<long>("product_id");

                    b.Property<int>("reason_id");

                    b.Property<byte>("status");

                    b.HasKey("Id");

                    b.HasIndex("appuser_id");

                    b.HasIndex("product_id");

                    b.HasIndex("reason_id");

                    b.ToTable("Tbl_ReportProduct");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.ReportReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<bool>("isenable");

                    b.Property<byte>("status");

                    b.Property<string>("title");

                    b.HasKey("Id");

                    b.ToTable("Tbl_ReportReason");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.Salsman", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("appuser_id");

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<bool>("isEnable");

                    b.Property<byte>("status");

                    b.Property<string>("user_id");

                    b.HasKey("Id");

                    b.HasIndex("appuser_id");

                    b.HasIndex("user_id");

                    b.ToTable("Tbl_Salsman");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.Sell", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("buy_id");

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<bool>("isenable");

                    b.Property<int>("price");

                    b.Property<long>("product_id");

                    b.Property<int>("qty");

                    b.Property<long>("removableprice");

                    b.Property<long>("seller_id");

                    b.Property<byte>("sellstatus");

                    b.Property<long>("shop_id");

                    b.Property<byte>("status");

                    b.Property<long>("totalprice");

                    b.Property<long>("totalsellprice");

                    b.HasKey("Id");

                    b.HasIndex("buy_id");

                    b.HasIndex("product_id");

                    b.HasIndex("seller_id");

                    b.HasIndex("shop_id");

                    b.ToTable("Tbl_Sell");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.Sellcheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<string>("desc");

                    b.Property<bool>("isenable");

                    b.Property<long>("sell_id");

                    b.Property<byte>("status");

                    b.HasKey("Id");

                    b.HasIndex("sell_id");

                    b.ToTable("Tbl_SellCheck");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.sellerBank", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BankNom");

                    b.Property<string>("bankname");

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<bool>("isenable");

                    b.Property<string>("owner");

                    b.Property<long>("seller_id");

                    b.Property<string>("shabNom");

                    b.Property<byte>("status");

                    b.Property<string>("user_id");

                    b.HasKey("Id");

                    b.HasIndex("seller_id");

                    b.HasIndex("user_id");

                    b.ToTable("Tbl_sellerBank");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.Shop", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("address");

                    b.Property<int>("cat_id");

                    b.Property<int>("city_id");

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<bool>("enable");

                    b.Property<string>("image");

                    b.Property<string>("lat");

                    b.Property<string>("lot");

                    b.Property<int>("ostan_id");

                    b.Property<long>("seller_id");

                    b.Property<byte>("status");

                    b.Property<string>("summary");

                    b.Property<string>("title");

                    b.Property<string>("user_id");

                    b.Property<int>("viewCount");

                    b.HasKey("Id");

                    b.HasIndex("cat_id");

                    b.HasIndex("city_id");

                    b.HasIndex("ostan_id");

                    b.HasIndex("seller_id");

                    b.HasIndex("user_id");

                    b.ToTable("Tbl_Shop");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.shopadvertise", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("appuser_id");

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<DateTime>("fromdateMiladi");

                    b.Property<string>("fromdateShamsi");

                    b.Property<string>("image");

                    b.Property<bool>("isenable");

                    b.Property<long>("shop_id");

                    b.Property<byte>("status");

                    b.Property<DateTime>("todateMiladi");

                    b.Property<string>("todateShamsi");

                    b.Property<string>("users_id");

                    b.HasKey("Id");

                    b.HasIndex("shop_id");

                    b.HasIndex("users_id");

                    b.ToTable("Tbl_ShopAdvertise");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.shopcomments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsEnable");

                    b.Property<long>("appuser_id");

                    b.Property<string>("body");

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<int>("replyto");

                    b.Property<long>("shop_id");

                    b.Property<byte>("status");

                    b.HasKey("Id");

                    b.HasIndex("appuser_id");

                    b.HasIndex("shop_id");

                    b.ToTable("Tbl_ShopComment");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.ShopPlanState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<DateTime>("expiredateml");

                    b.Property<string>("expiredatesh");

                    b.Property<int>("plan_id");

                    b.Property<long>("shop_id");

                    b.Property<DateTime>("startdateml");

                    b.Property<string>("startdatesh");

                    b.Property<byte>("status");

                    b.HasKey("Id");

                    b.HasIndex("plan_id");

                    b.HasIndex("shop_id");

                    b.ToTable("Tbl_ShopPlanState");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.Size", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("cat_id");

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<bool>("isEnable");

                    b.Property<string>("name");

                    b.Property<byte>("status");

                    b.HasKey("Id");

                    b.HasIndex("cat_id");

                    b.ToTable("Tbl_Size");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.SizeCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("cat_id");

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<int>("size_id");

                    b.Property<byte>("status");

                    b.HasKey("Id");

                    b.HasIndex("cat_id");

                    b.HasIndex("size_id");

                    b.ToTable("Tbl_SizeCategory");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.UserAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("address");

                    b.Property<long>("appuser_id");

                    b.Property<int>("city_id");

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<bool>("isActive");

                    b.Property<bool>("isenable");

                    b.Property<string>("lat");

                    b.Property<string>("lot");

                    b.Property<string>("mobile");

                    b.Property<string>("name");

                    b.Property<int>("ostan_id");

                    b.Property<string>("phone");

                    b.Property<string>("postalcode");

                    b.Property<byte>("status");

                    b.HasKey("Id");

                    b.HasIndex("appuser_id");

                    b.HasIndex("city_id");

                    b.HasIndex("ostan_id");

                    b.ToTable("Tbl_Useraddress");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.UserAlarm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("appuser_id");

                    b.Property<string>("body");

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<bool>("isenable");

                    b.Property<byte>("status");

                    b.Property<string>("title");

                    b.HasKey("Id");

                    b.HasIndex("appuser_id");

                    b.ToTable("Tbl_UserAlarm");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.UserApp", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("User_id");

                    b.Property<string>("birthdate");

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<string>("email");

                    b.Property<string>("firstName");

                    b.Property<byte>("gender");

                    b.Property<string>("image");

                    b.Property<bool>("isEnable");

                    b.Property<string>("lastName");

                    b.Property<string>("mobile");

                    b.Property<string>("mobileActiveCode");

                    b.Property<bool>("mobileActiveStatus");

                    b.Property<string>("nationalcode");

                    b.Property<string>("phone");

                    b.Property<byte>("status");

                    b.Property<string>("token");

                    b.Property<byte>("type");

                    b.HasKey("Id");

                    b.HasIndex("User_id");

                    b.ToTable("Tbl_UserApp");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.workerBanner", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("appuser_id");

                    b.Property<int>("category_id");

                    b.Property<int>("city_id");

                    b.Property<DateTime>("dateMiladi");

                    b.Property<string>("dateShamsi");

                    b.Property<string>("desc");

                    b.Property<string>("image");

                    b.Property<bool>("isenable");

                    b.Property<int>("ostan_id");

                    b.Property<byte>("status");

                    b.Property<string>("title");

                    b.Property<DateTime>("todate");

                    b.Property<int>("viewcount");

                    b.HasKey("Id");

                    b.HasIndex("appuser_id");

                    b.HasIndex("category_id");

                    b.HasIndex("city_id");

                    b.HasIndex("ostan_id");

                    b.ToTable("Tbl_Banner");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.ApplicationRoles")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.ApplicationUsers")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.ApplicationUsers")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.ApplicationRoles")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.ApplicationUsers")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.ApplicationUsers")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.AdvertisePlanState", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.shopadvertise", "Tbl_Shopadv")
                        .WithMany()
                        .HasForeignKey("adv_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.Plan", "Tbl_Plan")
                        .WithMany()
                        .HasForeignKey("plan_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.Appsetting", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.ApplicationUsers", "user")
                        .WithMany()
                        .HasForeignKey("user_id");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.bannerImage", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.workerBanner", "Tbl_WorkerBanner")
                        .WithMany()
                        .HasForeignKey("banner_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.Buy", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.UserApp", "Tbl_UserApp")
                        .WithMany()
                        .HasForeignKey("buyer_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.UserAddress", "Tbl_UserAddress")
                        .WithMany()
                        .HasForeignKey("buyeradd_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.Product", "Tbl_Product")
                        .WithMany()
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.Shop", "Tbl_Shop")
                        .WithMany()
                        .HasForeignKey("shop_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.Buycheck", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.Buy", "Tbl_Buy")
                        .WithMany()
                        .HasForeignKey("buy_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.Checkout", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.sellerBank", "Tbl_sellerBank")
                        .WithMany()
                        .HasForeignKey("bank_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.Salsman", "Tbl_Salsman")
                        .WithMany()
                        .HasForeignKey("seller_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.Shop", "Tbl_Shop")
                        .WithMany()
                        .HasForeignKey("shop_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.CheckoutRequest", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.sellerBank", "Tbl_sellerbank")
                        .WithMany()
                        .HasForeignKey("bank_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.Salsman", "Tbl_Salsman")
                        .WithMany()
                        .HasForeignKey("seller_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.Shop", "Tbl_Shop")
                        .WithMany()
                        .HasForeignKey("shop_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.City", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.Ostan", "Tblostan")
                        .WithMany()
                        .HasForeignKey("ostan_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.Comment", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.UserApp", "Tbl_UserApp")
                        .WithMany()
                        .HasForeignKey("appuser_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.Product", "Tbl_Products")
                        .WithMany()
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.ContactUs", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.UserApp", "Tbl_UserApp")
                        .WithMany()
                        .HasForeignKey("appuser_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.FollowShop", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.Shop", "shop")
                        .WithMany()
                        .HasForeignKey("shop_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.UserApp", "TblUserApp")
                        .WithMany()
                        .HasForeignKey("userapp_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.Order", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.UserApp", "Tbl_UserApp")
                        .WithMany()
                        .HasForeignKey("appuser_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.orderDetail", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.Order", "Tbl_Order")
                        .WithMany()
                        .HasForeignKey("order_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.Product", "Tbl_Product")
                        .WithMany()
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.Shop", "Tbl_Shop")
                        .WithMany()
                        .HasForeignKey("shop_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.payment", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.UserApp", "Tbl_UserApp")
                        .WithMany()
                        .HasForeignKey("appuser_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.ProdProp", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.Product", "Tbl_Product")
                        .WithMany()
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.Property", "Tbl_Property")
                        .WithMany()
                        .HasForeignKey("property_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.Product", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.ApplicationUsers", "user")
                        .WithMany()
                        .HasForeignKey("User_id");

                    b.HasOne("ShopPanel.Models.Domain.ProductBrand", "brand")
                        .WithMany()
                        .HasForeignKey("brand_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.Category", "Tbl_Category")
                        .WithMany()
                        .HasForeignKey("cat_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.Salsman", "Tbl_Salsman")
                        .WithMany()
                        .HasForeignKey("seller_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.Shop", "Tbl_Shop")
                        .WithMany()
                        .HasForeignKey("shop_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.ProductColor", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.Color", "Tbl_color")
                        .WithMany()
                        .HasForeignKey("color_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.Product", "Tbl_Product")
                        .WithMany()
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.ProductGallary", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.Product", "product")
                        .WithMany()
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.ProductProperties", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.Product", "Tbl_Product")
                        .WithMany()
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.Properties", "Tbl_Properties")
                        .WithMany()
                        .HasForeignKey("properties_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.PropertiesValue", "Tbl_PropertiesValue")
                        .WithMany()
                        .HasForeignKey("propertiesvalue_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.ProductSeller", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.Product", "Tbl_Product")
                        .WithMany()
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.Salsman", "Tbl_Salsman")
                        .WithMany()
                        .HasForeignKey("seller_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.Shop", "Tbl_Shop")
                        .WithMany()
                        .HasForeignKey("shop_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.ProductSize", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.Product", "Tbl_Product")
                        .WithMany()
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.Size", "Tbl_Size")
                        .WithMany()
                        .HasForeignKey("size_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.Properties", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.Category", "Tbl_Category")
                        .WithMany()
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.PropertiesValue", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.Properties", "Tbl_Properties")
                        .WithMany()
                        .HasForeignKey("properties_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.Property", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.Category", "Tbl_Category")
                        .WithMany()
                        .HasForeignKey("cat_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.Part", "Tbl_Part")
                        .WithMany()
                        .HasForeignKey("part_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.ReportProduct", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.UserApp", "Tbl_UserApp")
                        .WithMany()
                        .HasForeignKey("appuser_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.Product", "Tbl_product")
                        .WithMany()
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.ReportReason", "Tbl_ReportReason")
                        .WithMany()
                        .HasForeignKey("reason_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.Salsman", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.UserApp", "Tbl_Userapp")
                        .WithMany()
                        .HasForeignKey("appuser_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.ApplicationUsers", "user")
                        .WithMany()
                        .HasForeignKey("user_id");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.Sell", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.Buy", "Tbl_Buy")
                        .WithMany()
                        .HasForeignKey("buy_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.Product", "Tbl_Product")
                        .WithMany()
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.Salsman", "Tbl_Salsman")
                        .WithMany()
                        .HasForeignKey("seller_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.Shop", "Tbl_Shop")
                        .WithMany()
                        .HasForeignKey("shop_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.Sellcheck", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.Sell", "Tbl_Sell")
                        .WithMany()
                        .HasForeignKey("sell_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.sellerBank", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.Salsman", "Tbl_Salsman")
                        .WithMany()
                        .HasForeignKey("seller_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.ApplicationUsers", "Tbl_User")
                        .WithMany()
                        .HasForeignKey("user_id");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.Shop", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.Category", "Tbl_Category")
                        .WithMany()
                        .HasForeignKey("cat_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.City", "Tblcity")
                        .WithMany()
                        .HasForeignKey("city_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.Ostan", "Tblostan")
                        .WithMany()
                        .HasForeignKey("ostan_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.Salsman", "salsman")
                        .WithMany()
                        .HasForeignKey("seller_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.ApplicationUsers", "user")
                        .WithMany()
                        .HasForeignKey("user_id");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.shopadvertise", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.Shop", "Shop")
                        .WithMany()
                        .HasForeignKey("shop_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.ApplicationUsers", "User")
                        .WithMany()
                        .HasForeignKey("users_id");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.shopcomments", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.UserApp", "Tbl_UserApp")
                        .WithMany()
                        .HasForeignKey("appuser_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.Shop", "Tbl_Shop")
                        .WithMany()
                        .HasForeignKey("shop_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.ShopPlanState", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.Plan", "Tbl_Plan")
                        .WithMany()
                        .HasForeignKey("plan_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.Shop", "Tbl_Shop")
                        .WithMany()
                        .HasForeignKey("shop_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.Size", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.Category", "Tbl_Category")
                        .WithMany()
                        .HasForeignKey("cat_id");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.SizeCategory", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.Category", "Tbl_Category")
                        .WithMany()
                        .HasForeignKey("cat_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.Size", "Tbl_Size")
                        .WithMany()
                        .HasForeignKey("size_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.UserAddress", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.UserApp", "Tbl_Userapp")
                        .WithMany()
                        .HasForeignKey("appuser_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.City", "Tbl_city")
                        .WithMany()
                        .HasForeignKey("city_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.Ostan", "Tbl_ostan")
                        .WithMany()
                        .HasForeignKey("ostan_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.UserAlarm", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.UserApp", "Tbl_Userapp")
                        .WithMany()
                        .HasForeignKey("appuser_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.UserApp", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.ApplicationUsers", "user")
                        .WithMany()
                        .HasForeignKey("User_id");
                });

            modelBuilder.Entity("ShopPanel.Models.Domain.workerBanner", b =>
                {
                    b.HasOne("ShopPanel.Models.Domain.UserApp", "Tbl_UserApp")
                        .WithMany()
                        .HasForeignKey("appuser_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.Category", "Tbl_Category")
                        .WithMany()
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.City", "Tbl_City")
                        .WithMany()
                        .HasForeignKey("city_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShopPanel.Models.Domain.Ostan", "Tbl_Ostan")
                        .WithMany()
                        .HasForeignKey("ostan_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
